services:
  # Servidor de Banco de Dados (MongoDB)
  mongodb:
    image: mongo:latest
    container_name: nexar-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - nexar-network
    environment:
      - MONGO_INITDB_DATABASE=nexar_db

  # Aplicação Nexar (Java + React)
  nexar-app:
    build: .
    container_name: nexar-service
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - nexar-network
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/nexar_db
      - SERVER_PORT=8080

networks:
  nexar-network:
    driver: bridge

volumes:
  mongodb_data: